### ISSUE TITLE
Return an error when the parsing of an SVG failed instead of an empty Tree

### ISSUE THREAD

**Issue by fschutt** [RazrFalcon/usvg#8]
It's really useful to know where the parsing failed. If you just "return an empty tree", there's no way of knowing if the parsing actually failed or if the file is empty or.. what the actual error was. Just let `Tree::from_str` return an error enum when there is an error.

**Comment by RazrFalcon** [comment]
By the SVG spec an invalid file should not prevent rendering. So if file is invalid I simply render an empty 100x100 image.

The idea is that `usvg` can't fail. At least after an initial DOM was parsed. 

I will think about what to do with parsing errors.

**Comment by fschutt** [comment]
Well, you can always do: `Tree::from_str(my_str).unwrap_or_else(|| EmptyImage::new() )` (sort-of like that). But it would still be good to know to know the error, if only for logging purposes.

I wouldn't assume that your crate is only being used for rendering, I wanted to use it for just parsing the file.

**Comment by RazrFalcon** [comment]
Ok.

Currently, this crate is a foundation for the [resvg](https://github.com/RazrFalcon/resvg). But it's intended as a separate library + CLI app.
